#Fichier de configuration de SignCTS-Reloaded

variables:

  #Connexion au REDIS
  redis-server: 'localhost'
  redis-port: '6379'
  redis-password: ''

  #Interval de temps en secondes où le plugin interroge Redis pour mettre à jour les panneaux
  update-interval: '15'

colors:

  #couleur de la chaîne "Temps d'attente"
  time: "&a"

  #couleur de la chaîne de l'heure
  waiting: "&a"

  #couleur de la chaîne "Indisponible"
  unavailable: "&c"

  #couleur des numéros de ligne
  lignes:
    A: "&c"
    B: "&3"
    C: "&6"
    D: "&2"
    E: "&5"
    F: "&a"
    G: "&1"
    H: "&4"
    L1: "&1"
    L3: "&a"
    L6: "&5"
    2: "&c"
    4: "&c"
    4a: "&c"
    10: "&6"
    12: "&3"
    13: "&d"
    14: "&b"
    15: "&b"
    17: "&d"
    19: "&d"
    22: "&b"
    24: "&b"
    27: "&a"
    29: "&2"
    30: "&e"
    31: "&d"
    40: "&e"
    41: "&b"
    42: "&5"
    43: "&c"
    44: "&3"
    45: "&6"
    50: "&e"
    57: "&6"
    60: "&6"
    62: "&a"
    63: "&3"
    64: "&d"
    67: "&2"
    70: "&6"
    70a: "&6"
    71: "&3"
    72: "&d"
    73: "&6"
    74: "&2"
    75: "&a"
    76: "&5"